name: Deploy to VPS on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/budgetin-be
            git pull origin main
            docker build -t alfarizi/budgetin-db:latest .
            docker stop budgetin-be || true
            docker rm budgetin-be || true
            docker run -d -p 8080:8080 \
              --env-file .env \
              --name budgetin-be alfarizi/budgetin-db:latest
