name: Deploy to VPS on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/budgetin-be
            git fetch --tags
            git checkout ${{ github.ref_name }} # checkout tag yang di-release
            docker build -t alfarizi/budgetin-db:latest .
            docker rm -f budgetin-be || true
            docker run -d -p 8080:8080 \
              -e APP_CORS_ALLOWED_ORIGIN=${{ secrets.APP_CORS_ALLOWED_ORIGIN }} \
              --name budgetin-be alfarizi/budgetin-db:latest

            # Opsional: tunggu container siap (cek port 8080)
            for i in {1..10}; do
              if curl -s http://localhost:8080/health || curl -s http://localhost:8080/; then
                echo "App is up!"
                break
              else
                echo "Waiting for app to be ready..."
                sleep 3
              fi
            done
